geoedgemap/geoedge/urls.py
from django.urls import path
from . import views


app_name = 'geoedge'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.user_login, name='login'),
    path('new_user/', views.new_user, name='new_user'),
    path('video/', views.video, name='video'),
    path('register/', views.register, name='register'),
    path('new_user/', views.new_user, name='new_user'),
    path('activate/<uidb64>/<token>/', views.activate,
         name='activate'),
    path('profile/', views.profile, name='profile'),
    path('user_data/', views.user_data, name='user_data'),
    path('user_data_update/', views.user_data_update, name='user_data_update'),
    path('user_update/', views.user_update, name='user_update'),
    path('group/<gid>/', views.group, name='group'),
    path('member_list/<gid>/', views.member_list, name='member_list'),
]

geoedgemap/geoedgemap/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from geoedge import views
from django.urls import path,include    


urlpatterns = [
    path('admin/', admin.site.urls),
    path('map/', include('map.urls', namespace='map')),
    path('', include('geoedge.urls', namespace='geoedge')),
    path('logout/$', views.user_logout, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geoedgemap/map/urls.py
from django.urls import include, path
from django.conf.urls import url

from . import views

app_name = 'map'
urlpatterns = [
    path('', views.index, name='index'),
    url('group/(?P<gid>[\w-]+)/$', views.index_group, name='index_group'),
    url('group/(?P<gid>[\w-]+)$', views.index_group, name='index_group'),
    url('view/(?P<map>[\w-]+)/(?P<gid>[\w-]+)$', views.map_view, name='map_view'),
    url('(?P<map>[\w-]+)/(?P<layer_type>[\w-]+)$', views.get_layer_data, name='get_layer_data'),
    url('group/(?P<gid>[\w-]+)/(?P<map>[\w-]+)/(?P<layer_type>[\w-]+)$', views.get_group_data, name='get_group_data'),
    url('post_layers/$', views.add_layer_file, name='post_layer_file'),
    url('post_upload/(?P<layer_id>[\w-]+)/$', views.upload_layer_files, name='post_upload'),
    url('load_layer_files/(?P<layerId>[\w-]+)/(?P<groupId>[\w-]+)/$', views.load_layer_files,
        name='load_layer_files'),
    url('layer_data/(?P<layer_id>[\w-]+)/(?P<groupId>[\w-]+)/$', views.layer_data, name='layer_data'),
	url('aaib_layer_data/(?P<layer_id>[\w-]+)/$', views.aaib_layer_data, name='aaib_layer_data'),
    url('layersdata/(?P<layerId>[\w-]+)/(?P<groupId>[\w-]+)/$', views.layers_data, name='layers_data'),
    url('mapsdata/(?P<layerId>[\w-]+)/(?P<groupId>[\w-]+)/$', views.map_data, name='map_data'),
    url('get_legends/(?P<mapID>[\w-]+)/(?P<groupId>[\w-]+)/$', views.map_get_legends, name='map_get_legends'),
    url('map_count/$', views.map_count, name='map_count'),
    url('map_group_count/(?P<groupId>[\w-]+)/$', views.map_group_count, name='map_group_count'),
    url('lastest_map/(?P<groupId>[\w-]+)/$', views.lastest_map, name='lastest_map'),
    url('lastest_news/(?P<groupId>[\w-]+)/$', views.lastest_News, name='lastest_news'),
    url('lastest_layer_data/(?P<groupId>[\w-]+)/$', views.get_lastest_layer_data, name='lastest_layer_data'),
    url('save_as_layers/$', views.save_as_new_drawing, name='save_as_layers'),
    url('save_layers_file/$', views.save_drawing_file, name='save_drawing_file'),
    url('save_as_map/$', views.save_as_map, name='save_as_map'),
    url('save_map_file/$', views.save_map_file, name='save_map_file'),
    url('save_layers/$', views.save_new_drawing, name='save_layers'),
    url('search_layers_list/(?P<layer_status_type>[\w-]+)/$', views.search_layers_list, name='search_layers_list'),
    url('search_public_layers_list/(?P<layer_status_type>[\w-]+)/$', views.search_public_layers_list, name='search_public_layers_list'),
    url('search_group_layers_list/(?P<layer_status_type>[\w-]+)/(?P<gid>[\w-]+)/$', views.search_group_layers_list, name='search_grouplayers_list'),
    url('searchbox_layers_list/(?P<gid>[\w-]+)/$', views.searchbox_layers_list, name='searchbox_layers_list'),
    url('save_as_map/$', views.save_as_map, name='save_as_map'),
    url('save_map_file/$', views.save_map_file, name='save_map_file'),
    url('save_layers/$', views.save_new_drawing, name='save_layers'),
    url('search_layers_list/(?P<layer_status_type>[\w-]+)/$', views.search_layers_list, name='search_layers_list'),
    url('search_group_layers_list/(?P<layer_status_type>[\w-]+)/(?P<gid>[\w-]+)/$', views.search_group_layers_list,
        name='search_grouplayers_list'),
    url('searchbox_layers_list/(?P<gid>[\w-]+)/$', views.searchbox_layers_list, name='searchbox_layers_list'),
    url('share_map/(?P<map>[\w-]+)/(?P<layer_type>[\w-]+)$', views.share_layer_data, name='share_layer_data'),
    url('my_map_data/$', views.my_map_data, name='my_map_data'),
    url('my_map_data_all/$', views.my_map_data_all, name='my_map_data_all'),
    url('data_update/$', views.data_update, name='data_update'),
    url('my_layer_data/$', views.my_layer_data, name='my_layer_data'),
    url('all_map_data/$', views.all_map_data, name='all_map_data'),
    url('all_layer_data/$', views.all_layer_data, name='all_layer_data'),
    url('my_group/$', views.my_group, name='my_group'),
    url('all_group/$', views.all_group, name='all_group'),
    url('data_delete/$', views.data_delete, name='data_delete'),
    url('add_group/$', views.add_group, name='add_group'),
    url('group_maps/(?P<gid>[\w-]+)/$', views.group_maps, name='group_maps'),
    url('group_layers/(?P<gid>[\w-]+)/$', views.group_layers, name='group_layers'),
    url('group_members/(?P<gid>[\w-]+)/$', views.group_members, name='group_members'),
    url('^group_update/$', views.group_update, name='group_update'),
    url('add_member/$', views.add_member, name='add_member'),
    url('superuser_update/$', views.superuser_update, name='superuser_update'),
    url('download_shp/$', views.download_shp, name='download_shp'),
    url('remove_downloaded/$', views.remove_downloaded, name='remove_downloaded'),
    url('get_layer_details/(?P<layerId>[\w-]+)/(?P<layerType>[\w-]+)/$', views.get_layer_details,
        name='get_layer_details'),
    url('remove_file/$', views.remove_file, name='remove_file'),
    url('province/$', views.province, name='province'),
    url('district/(?P<province>[\w-]+)/$', views.district, name='district'),
    url('asc/(?P<district>[\w-]+)/$', views.asc, name='asc'),
    url('ds/(?P<province>[\w-]+)/(?P<district>[\w-]+)/$', views.ds, name='ds'),
    url('gn/(?P<province>[\w-]+)/(?P<district>[\w-]+)/(?P<ds>[\w-]+)/$', views.gn, name='gn'),
    url('aaib_section/$', views.aaib_section, name='aaib_section'),
    url('aaib_polygon/$', views.aaib_polygon, name='aaib_polygon'),
    url('aaib_data/$', views.aaib_data, name='aaib_data'),
    url('aaib_one_polygon/$', views.aaib_one_polygon, name='aaib_one_polygon'),
]

geoedgemap/geoedge/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_image = models.TextField(max_length=200, blank=True)
    user_descri = models.TextField(blank=True)
    created_at = models.DateTimeField(null=True, blank=True)
    updated_at = models.DateTimeField(null=True, blank=True)
    by_user_id = models.IntegerField(default='0')
 

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

geoedgemap/geoedge/views.py
from __future__ import unicode_literals
import os

from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
from django.conf import settings
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.core.files.storage import FileSystemStorage
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from .tokens import account_activation_token
from django.core.mail import EmailMessage
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.contrib.auth import update_session_auth_hash

from datetime import datetime, date

from .register_forms import RegisterForm
from map.models import Groups, Group_member, Group_layerfiles, Group_layer_draw

import urllib.request
import urllib.parse
import json

import urllib
import urllib3

def index(request):
    args = {'user': request.user}
    return render(request,'geoedge/main_content.html', args)

def special(request):
    return HttpResponse("You are logged in !")

def user_logout(request):
    aaib_taken = ''
    try:
        aaib_taken = request.session['access_token']
        del request.session['remember_me']
        del request.session['access_token']
    except:
        pass
    logout(request)
    return render(request, 'geoedge/base.html')

def user_login(request):
    access_token = request.GET.get('access-token')
    if access_token is None and request.method == 'GET':
        # return HttpResponseForbidden('403 Forbidden', content_type='text/html')
        return render(request, 'geoedge/error.html', {'error': 'Invalid Token'})

    if access_token == '' and request.method == 'GET':
        # return HttpResponseForbidden('403 Forbidden', content_type='text/html')
        return render(request, 'geoedge/error.html', {'error': 'Invalid Token'})

    try:
        main_server = settings.AAIB_URL
        url = str(main_server) + 'api/api/user-map-engine&access-token=' + str(access_token)
        values = {'access_token': access_token}
        http = urllib3.PoolManager()
        r = http.request('POST', url, fields=values)
        result = json.loads(r.data.decode('utf-8'))

        if result['status'] != 1:
            return render(request, 'geoedge/error.html', {'error': 'Invalid Token'})

        aaib_user = aaibUser(result)
        user = authenticate(username=result['username'], password=aaib_user['password'])
        if user:
            login(request, user)
            request.session['remember_me'] = result['username']
            request.session['access_token'] = access_token
            settings.SESSION_EXPIRE_AT_BROWSER_CLOSE = True
            return HttpResponseRedirect(reverse('map:index'))
        else:
            return render(request, 'geoedge/login.html', {'error': 'User could not access.'})
    except:
        return render(request, 'geoedge/error.html', {'error': 'Invalid Token'})

def aaibUser(request):

    if(request['username'] is None):
        return False

    if (request['full_name'] is None):
        return False

    if (request['email'] is None):
        return False;

    if (request['access_token'] is None):
        return False;

    if User.objects.filter(username=request['username']).exists():
        aaib_user = aaibUerUpdate(request)
    else:
        aaib_user = aaibUerCreate(request)

    if(aaib_user['status'] != 1):
        return render(request, 'geoedge/error.html', {'error': 'User could not access.'})
    return aaib_user;

def aaibUerUpdate(request):
    nowTime = datetime.now()
    user = User.objects.get(username=request['username'])
    password = nowTime.strftime("%Y%m%d%H%M%S") + str(request['access_token'])
    user.first_name = request['full_name']
    user.set_password(password)
    user.profile.updated_at = nowTime.strftime("%Y-%m-%d %H:%M:%S")
    user.save()
    return {'password': password, 'status': 1, 'user_id': user.pk}

def aaibUerCreate(request):
    nowTime = datetime.now()
    password = nowTime.strftime("%Y%m%d%H%M%S")+str(request['access_token'])
    # Create the user:
    user = User.objects.create_user(request['username'], request['email'], password)
    user.is_active = True
    user.first_name = request['full_name']
    user.set_password(password)
    user.save()
    user.profile.created_at = nowTime.strftime("%Y-%m-%d %H:%M:%S")
    user.profile.updated_at = nowTime.strftime("%Y-%m-%d %H:%M:%S")
    user.profile.by_user_id = user.pk
    user.save()
    userId = user.pk
    return {'password': password, 'status':1, 'user_id':userId}

def register(request):
    template = 'geoedge/register.html'
    nowTime = datetime.now()


    if request.method == 'POST':
        reg_description = request.POST['description']
        form = RegisterForm(request.POST)
        if form.is_valid():
            
            ''' reCAPTCHA validation '''

            recaptcha_response = request.POST.get('g-recaptcha-response')
            url = 'https://www.google.com/recaptcha/api/siteverify'
            values = {
                'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                'response': recaptcha_response
            }
            http = urllib3.PoolManager()
            r = http.request('POST', url, fields=values)
            result = json.loads(r.data.decode('utf-8'))


            ''' /reCAPTCHA validation '''
            
            
            
            if result['success'] == False:
                return render(request, template, {
                    'form': form,
                    'error_message': 'Invalid reCAPTCHA. Please try again.'
                })
            elif User.objects.filter(username=form.cleaned_data['username']).exists():
                return render(request, template, {
                    'form': form,
                    'error_message': 'Username already exists.'
                })
            elif User.objects.filter(email=form.cleaned_data['email']).exists():
                return render(request, template, {
                    'form': form,
                    'error_message': 'Email already exists.'
                })
            elif form.cleaned_data['password'] != form.cleaned_data['password_repeat']:
                return render(request, template, {
                    'form': form,
                    'error_message': 'Passwords do not match.'
                })
            else:
                # Create the user:
                user = User.objects.create_user(
                    form.cleaned_data['username'],
                    form.cleaned_data['email'],
                    form.cleaned_data['password']
                )

            if(request.user):
                by_user_id = request.user.pk
            else:
                by_user_id = 0

            user.is_active = False
            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']
            user.profile.user_descri = reg_description
            # user.photo = post_inpt['']
            user.profile.created_at = nowTime.strftime("%Y-%m-%d %H:%M:%S")
            user.profile.updated_at = nowTime.strftime("%Y-%m-%d %H:%M:%S")
            user.profile.by_user_id = by_user_id
            user.save()
            userId = user.pk

            # Store Photo
            try:
                photo = request.FILES['photo']
                ext = photo.name.split('.')[-1]
                photoName = 'profile_' + str(userId) + '.' + ext

                fs = FileSystemStorage()
                file_path = 'media/profile/' + photoName
                media_root = settings.MEDIA_ROOT
                full_filepath = os.path.abspath(os.path.join(os.path.dirname(media_root), file_path))
                filename = fs.save(full_filepath, photo)

                user.profile.profile_image = photoName
                user.profile.updated_at = nowTime.strftime("%Y-%m-%d %H:%M:%S")
                user.save()
            except:
                photoName = ''
            # /Store Photo

            # Send Email
            current_site = get_current_site(request)
            mail_subject = 'Activate your GeoEdgeMap account.'
            message = render_to_string('geoedge/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            
            email_from = settings.EMAIL_HOST_USER
            recipient_list = [to_email,]
            
            send_mail(mail_subject, message, email_from, recipient_list)

            # /Send Email

            reform = RegisterForm()
            return render(request, template, {
                'success_message': 'Please confirm your email address to complete the registration',
                'form': reform
            })
    else:
        form = RegisterForm()
        return render(request, template, {'form': form})


def new_user(request):
    template = 'geoedge/create_user.html'
    nowTime = datetime.now()


    if request.method == 'POST':
        reg_description = request.POST['description']
        form = RegisterForm(request.POST)
        if form.is_valid():
            if User.objects.filter(username=form.cleaned_data['username']).exists():
                return render(request, template, {
                    'form': form,
                    'error_message': 'Username already exists.'
                })
            elif User.objects.filter(email=form.cleaned_data['email']).exists():
                return render(request, template, {

geoedgemap/geoedge/templates/geoedge/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}/activate/{{uid}}/{{token}}
{% endautoescape %}

geoedgemap/geoedge/templates/geoedge/base.html
{% extends 'base_page.html' %}
{% load static %}
{% block content %}
<div class="container" style="margin-top:20%;">
    <div class="col-md-12">
        <center>
            <b><h1>
                <strong>AIMS GeoEDGE Pro</strong>
            </h1></b>
        </center>
    </div>

</div>
{% endblock %}

geoedgemap/geoedge/templates/geoedge/create_user.html
{% extends 'base_login.html' %}
{% block content %}

<style>
  .btn-primary {height:40px;}
  .btn-lg {padding:0px;}
</style>

<div id="wrap">
    <div class="container" >
	    <div class="row">
            <div class="col-md-12">
                <!--<span style="float:right;margin-right:15%;margin-top:5px;">  Already Have an Account? -<a href="login.php"> Sign In </a></span>-->

                <form id="register_form" accept-charset="utf-8" class="form" method="post" role="form" style="width:70%;" enctype="multipart/form-data" action="{% url 'geoedge:new_user' %}">
                {% csrf_token %}

                  <legend>Create User</legend>

                    {% if error_message %}
                        <p class="bg-danger p-d ml-b">{{ error_message }}</p>
                    {% endif %}

                    {% if success_message %}
                        <p class="bg-success p-d ml-b">{{ success_message }}</p>
                    {% endif %}

                        <div class="row">
                            <div class="col-xs-6 col-md-6">
                                <!--<input type="text" id="reg_firstname" name="firstname" value="" class="form-control input-lg" placeholder="First Name"/>-->
                                {{ form.first_name }}
                            </div>
                            <div class="col-xs-6 col-md-6">
                                <!--<input type="text" id="reg_lastname" name="lastname" value="" class="form-control input-lg" placeholder="Last Name"/>-->
                                {{ form.last_name }}
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-xs-6 col-md-6">
                                <!--<input type="text" id="reg_username" name="username" value="" class="form-control input-lg" placeholder="Username"/>-->
                                {{ form.username }}
                            </div>
                            <div class="col-xs-6 col-md-6">
                                <!--<input type="text" id="reg_email" name="email" value="" class="form-control input-lg" placeholder="Your Email"/>-->
                                {{ form.email }}
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-xs-6 col-md-6">
                                <!--<input type="password" id="reg_password" name="password" value="" class="form-control input-lg" placeholder="Password"  />-->
                                {{ form.password }}
                            </div>
                            <div class="col-xs-6 col-md-6">
                                <!--<input type="password" id="reg_confirmpassword" value="" class="form-control input-lg" placeholder="Confirm Password"  />-->
                                {{ form.password_repeat }}
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <input name="photo" type="file" accept="image/*" class="filestyle" data-buttonName="btn-primary" style="height:40px;" />
                            </div>

                            <div class="col-md-12">
                                <textarea class="form-control" id="reg_description" name="description" placeholder="Description" style="height:150px;"></textarea>
                            </div>
                        </div>


                        <p id="res_error_msg" style="color:#DF0000; font-size: 15px; font-weight: bold;"></p>
                        <!--<span class="help-block text-warning">New username is the full email address you used to create new account.</span>-->
                        <span class="help-block">By clicking Create account, you agree to our Terms and that you have read our Data Use Policy.</span><br>

                        <button id="register" class="btn btn-lg btn-primary btn-block">Create account</button><br>
                </form>
            </div>
        </div>
    </div>
</div>
<br>
{% endblock %}

geoedgemap/geoedge/templates/geoedge/error.html
{% extends 'base_page.html' %}
{% load static %}
{% block content %}
<div class="container" style="margin-top:20%;">
    <div class="col-md-12">
        <center>
            <b><h1>
                {% if error %}
                    <strong>{{ error }}</strong>
                {% endif %}
            </h1></b>
        </center>
    </div>

</div>
{% endblock %}

geoedgemap/geoedge/templates/geoedge/login.html
{% extends 'base_login.html' %}
{% load static %}
{% block content %}
<div class="banner" style="height:90%;overflow:hidden;">
	<div class="container">

		<div class="banner-info">

		    <div class="col-md-12 column">
                <center>
                    <img src="{% static 'img/logo.png' %}">
                </center>

			    <h1>VISUALIZE <span>YOUR DATA</span> AS MAPS</h1>
                <p><b>GeoEDGE - For Smarter Business</b></p>
			</div>

            <div class="col-md-12">
                <center>
                    {% if success_message %}
                        <p class="bg-success p-d ml-b">{{ success_message }}</p>
                    {% endif %}
                </center>
            </div>


			<div class="col-md-6 column" style="" id="bor">
			    <center>
			        <h2 style="margin-left:170px;">SEE IN ACTION</h2>
			        <br>
			        <div class="video">
                        <a class="play-icon popup-with-zoom-anim" href="#small-dialog">
                            <span style="margin-left:50px;"> </span>
                        </a>

					<!-- pop-up-box -->
                        <link rel="stylesheet" type="text/css" href="{% static 'css/popuo-box.css' %}" media="all" />
                        <script type="text/javascript" src="{% static 'js/jquery.magnific-popup.js' %}"></script>
                    <!--//pop-up-box -->

						<div id="small-dialog" style="height:340px;" class="mfp-hide">
							<iframe src="{% url 'geoedge:video' %}" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
						</div>

						<script>

						    function formNull(){
							$('#username').val(null);
                            $('#password').val(null);
		                    }
							$(document).ready(function() {

							$('.popup-with-zoom-anim').magnificPopup({
								type: 'inline',
								fixedContentPos: false,
								fixedBgPos: true,
								overflowY: 'auto',
								closeBtnInside: true,
								preloader: false,
								midClick: true,
								removalDelay: 300,
								autoplay: true,
								mainClass: 'my-mfp-zoom-in'
							});

							$('#btn-login').click(function(e){
                             e.preventDefault();
	                         login();
                            })

							});


						</script>
                    </div>
                    <br>
					<!--<h4 style="margin-left:170px;"><a href="#" >or Login As Public Users</a></h4>-->
			    </center>
			    <br>
		    </div>


		    <div class="col-md-6 column">
                <br>
                <center>

                    <section id="login">
                        <div class="container">
                            <div class="row">
                                <div class="col-xs-3" style="margin-left:30px;">

                                    <div class="form-wrap">

                                        <h2 style="">LOGIN</h2>

                                        {% if error %}
                                            <strong id="error_msg" style="color:red;float:left; font-weight: 400;font-style: italic;">{{ error }}</strong>
                                        {% endif %}


                                        <!--<form role="form" id="login-form" autocomplete='off'>-->
                                        <form role="form" id="login-form" method="post" action="{% url 'geoedge:login' %}" autocomplete='off'>
                                        {% csrf_token %}
                                            <div class="form-group">
                                                <label for="email" class="sr-only">User name</label>
                                                <input type="text" name="username" id="username" autocomplete='off' class="form-control" placeholder="E Mail">
                                            </div>

                                            <div class="form-group">
                                                <label for="key" class="sr-only">Password</label>
                                                <input type="password" name="password" id="password" autocomplete='off' class="form-control" placeholder="Password">
                                            </div>

                                                <input type="hidden" name="aaib_token" id="aaib_token"  value="{{ access_token }}">

                                            <div class="form-group text-center" style="float:left;">
                                                <input type="checkbox" tabindex="3" class="" name="remember" id="remember">
                                                <label for="remember" style="position:relative;top:-2px;"><small> Remember Me</small></label>
                                            </div>

                                            <span style="float:right;margin-top:-7px;"><a id="modal-105078" href="#modal-container-105078" role="button" class="btn" data-toggle="modal"><small>Forgot Password?</small></a></span>

                                            <!--<input type="submit" id="btn-login" class="btn btn-custom btn-lg btn-block" value="Log in" />-->
                                            <input type="submit" class="btn btn-custom btn-lg btn-block"  name="" value="Login">

                                        </form>

<!--                                        <a href="{% url 'geoedge:register' %}" ><span style="color:#D64937;">Don't have an account?</span> sign up now</a>-->

                                    </div>
                                    <br>
                                </div>
                            </div>
                        </div>
                    </section>

                     <!-- modal -->
                    <div class="modal fade forget-modal" tabindex="-1" role="dialog" aria-labelledby="myForgetModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-sm">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal">
                                        <span aria-hidden="true">×</span>
                                        <span class="sr-only">Close</span>
                                    </button>
                                    <h4 class="modal-title">Recovery password</h4>
                                </div>

                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                    <button type="button" class="btn btn-custom">Recovery</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /modal -->

                </center>
		    </div>
	    </div>

    </div>
</div>


<!--forget password -->
<div class="row clearfix">
    <div class="col-md-12 column">

        <div class="modal fade" id="modal-container-105078" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

            <center>
				<div class="modal-dialog" >
					<div class="modal-content" style="width:60%;">
						<div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h4 class="modal-title" id="myModalLabel">Recovery password</h4>
						</div>
						<div class="modal-body">
				            <p>Type your email account</p>
				            <input type="email" name="recovery-email" id="recovery-email" class="form-control" autocomplete="off">
			            </div>
						<div class="modal-footer">
							 <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
							 <button type="button" class="btn btn-primary" onclick="sendMail()">Send Password</button>
						</div>
					</div>
				</div>
            </center>

        </div>

    </div>
</div>
<!--/forget password -->

<!--footer-->
<div class="footer">
	<div class="container">
		<div class="footer-grids">
			<div class="footer-left">
				<p>COPYRIGHT &COPY; <script>document.write(new Date().getFullYear())</script>  <a href="http://geoedge.lk/"> GeoEDGE</a></p>
			</div>
			<div class="clearfix"></div>
		</div>
	</div>
</div>
<!--/footer-->

{% endblock %}

geoedgemap/geoedge/templates/geoedge/profile.html
{% extends 'base_login.html' %}
{% load static %}
{% load staticfiles%}

{% block content %}

<h1>Test</h1>

{% endblock %}